project_id = "vscbltneuicgewulpnmh"

[functions.fetch-provider-services]
verify_jwt = false

[functions.forward-order]
verify_jwt = false

[functions.sync-order-status]
verify_jwt = false

[functions.sync-rates]
verify_jwt = false
